version: "3.8"
services:
  app:
    image: node
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: /bin/sh -c "npm install && npx nodemon --exec ts-node ./server/server.ts"
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  webpack-dev-server:
    image: node
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules # 이 라인도 동일하게 추가하여 호스트의 node_modules와 분리
    working_dir: /app
    command: /bin/sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dkrlaos1
      POSTGRES_USER: kimjongyoon
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
