version: "3.8"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: /bin/sh -c "npm run compile&& npm run build && npm run migration:run && npm run start"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dkrlaos1
      POSTGRES_USER: kimjongyoon
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
