version: "3.8"
services:
  app:
    image: node
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.aws:/root/.aws
    working_dir: /app
    command: /bin/sh -c "./entrypoint.sh app"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - AWS_SDK_LOAD_CONFIG=1

  webpack-dev-server:
    image: node
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.aws:/root/.aws
    working_dir: /app
    command: /bin/sh -c "./entrypoint.sh webpack-dev-server"
    environment:
      - NODE_ENV=development
      - AWS_SDK_LOAD_CONFIG=1
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dkrlaos1
      POSTGRES_USER: kimjongyoon
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
