version: '3.8'
services:
  app:
    image: node
    ports:
      - '3004:3004'
    volumes:
      - .:/app
    working_dir: /app
    command: node express.mjs
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dkrlaos1
    ports:
      - '5432:5432'
