version: "3.8"
services:
  app:
    image: node
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    command: npx nodemon ./server/sever.js
    depends_on:
      - db

  webpack-dev-server:
    image: node
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dkrlaos1
      POSTGRES_USER: kimjongyoon
    ports:
      - "5432:5432"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
