version: "3.8"
services:
  app:
    image: node
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    command: npx nodemon ./server/sever.js
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dkrlaos1
    ports:
      - "5432:5432"
