services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app

    working_dir: /app
    command: /bin/sh -c "npm install &&npm run build && npm run build:server&&npm run migration:generate && npm run migration:run  && npm run start"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=kimjongyoon
      - DB_PASSWORD=dkrlaos1
      - DB_NAME=postgres
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dkrlaos1
      POSTGRES_USER: kimjongyoon
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
